import type { Module } from '../types';

export const MOCK_MODULES: Module[] = [
  {
    id: 'mod_01',
    number: 1,
    title: 'Foundations of Business English',
    description: 'Core vocabulary and expressions for everyday professional settings.',
    level: 'A2–B1',
    color: '#2563EB',
    status: 'completed',
    completedLessons: 5,
    totalLessons: 5,
    totalXP: 500,
    lessons: [
      {
        id: 'l_01_1',
        title: 'Workplace Vocabulary',
        duration: '8 min',
        xp: 100,
        status: 'completed',
        skill: 'vocabulary',
      },
      {
        id: 'l_01_2',
        title: 'Formal vs Informal Register',
        duration: '10 min',
        xp: 100,
        status: 'completed',
        skill: 'writing',
      },
      {
        id: 'l_01_3',
        title: 'Introductions & Small Talk',
        duration: '12 min',
        xp: 100,
        status: 'completed',
        skill: 'speaking',
      },
      {
        id: 'l_01_4',
        title: 'Email Basics',
        duration: '9 min',
        xp: 100,
        status: 'completed',
        skill: 'writing',
      },
      {
        id: 'l_01_5',
        title: 'Listening: Office Conversations',
        duration: '10 min',
        xp: 100,
        status: 'completed',
        skill: 'listening',
      },
    ],
  },
  {
    id: 'mod_02',
    number: 2,
    title: 'Meetings & Presentations',
    description: 'Confidently lead and participate in meetings, present ideas clearly.',
    level: 'B1',
    color: '#7C3AED',
    status: 'in_progress',
    completedLessons: 2,
    totalLessons: 6,
    totalXP: 600,
    lessons: [
      {
        id: 'l_02_1',
        title: 'Meeting Phrases & Expressions',
        duration: '10 min',
        xp: 100,
        status: 'completed',
        skill: 'vocabulary',
      },
      {
        id: 'l_02_2',
        title: 'Giving Your Opinion',
        duration: '12 min',
        xp: 100,
        status: 'completed',
        skill: 'speaking',
      },
      {
        id: 'l_02_3',
        title: 'Structuring a Presentation',
        duration: '15 min',
        xp: 100,
        status: 'available',
        skill: 'writing',
      },
      {
        id: 'l_02_4',
        title: 'Handling Q&A Sessions',
        duration: '11 min',
        xp: 100,
        status: 'locked',
        skill: 'speaking',
      },
      {
        id: 'l_02_5',
        title: 'Listening: Boardroom Discussion',
        duration: '13 min',
        xp: 100,
        status: 'locked',
        skill: 'listening',
      },
      {
        id: 'l_02_6',
        title: 'Grammar: Conditional Sentences',
        duration: '10 min',
        xp: 100,
        status: 'locked',
        skill: 'grammar',
      },
    ],
  },
  {
    id: 'mod_03',
    number: 3,
    title: 'Negotiation & Persuasion',
    description: 'Master techniques to negotiate deals and persuade stakeholders.',
    level: 'B1–B2',
    color: '#C8102E',
    status: 'available',
    completedLessons: 0,
    totalLessons: 6,
    totalXP: 600,
    lessons: [
      {
        id: 'l_03_1',
        title: 'Negotiation Vocabulary',
        duration: '9 min',
        xp: 100,
        status: 'available',
        skill: 'vocabulary',
      },
      {
        id: 'l_03_2',
        title: 'Persuasive Language',
        duration: '11 min',
        xp: 100,
        status: 'locked',
        skill: 'speaking',
      },
      {
        id: 'l_03_3',
        title: 'Writing Proposals',
        duration: '14 min',
        xp: 100,
        status: 'locked',
        skill: 'writing',
      },
      {
        id: 'l_03_4',
        title: 'Listening: Contract Discussion',
        duration: '12 min',
        xp: 100,
        status: 'locked',
        skill: 'listening',
      },
      {
        id: 'l_03_5',
        title: 'Grammar: Modal Verbs',
        duration: '10 min',
        xp: 100,
        status: 'locked',
        skill: 'grammar',
      },
      {
        id: 'l_03_6',
        title: 'Role Play: Closing a Deal',
        duration: '15 min',
        xp: 100,
        status: 'locked',
        skill: 'speaking',
      },
    ],
  },
  {
    id: 'mod_04',
    number: 4,
    title: 'Reports & Professional Writing',
    description: 'Write clear, structured business reports and professional documents.',
    level: 'B2',
    color: '#059669',
    status: 'locked',
    completedLessons: 0,
    totalLessons: 5,
    totalXP: 500,
    lessons: [
      {
        id: 'l_04_1',
        title: 'Report Structure',
        duration: '10 min',
        xp: 100,
        status: 'locked',
        skill: 'writing',
      },
      {
        id: 'l_04_2',
        title: 'Formal Vocabulary for Reports',
        duration: '9 min',
        xp: 100,
        status: 'locked',
        skill: 'vocabulary',
      },
      {
        id: 'l_04_3',
        title: 'Charts & Data Language',
        duration: '11 min',
        xp: 100,
        status: 'locked',
        skill: 'writing',
      },
      {
        id: 'l_04_4',
        title: 'Grammar: Passive Voice',
        duration: '10 min',
        xp: 100,
        status: 'locked',
        skill: 'grammar',
      },
      {
        id: 'l_04_5',
        title: 'Listening: Analyst Briefing',
        duration: '13 min',
        xp: 100,
        status: 'locked',
        skill: 'listening',
      },
    ],
  },
  {
    id: 'mod_05',
    number: 5,
    title: 'Leadership & Team Communication',
    description: 'Language skills to lead teams, give feedback, and resolve conflict.',
    level: 'B2–C1',
    color: '#D97706',
    status: 'locked',
    completedLessons: 0,
    totalLessons: 6,
    totalXP: 600,
    lessons: [
      {
        id: 'l_05_1',
        title: 'Leadership Vocabulary',
        duration: '9 min',
        xp: 100,
        status: 'locked',
        skill: 'vocabulary',
      },
      {
        id: 'l_05_2',
        title: 'Giving Constructive Feedback',
        duration: '12 min',
        xp: 100,
        status: 'locked',
        skill: 'speaking',
      },
      {
        id: 'l_05_3',
        title: 'Conflict Resolution Language',
        duration: '11 min',
        xp: 100,
        status: 'locked',
        skill: 'speaking',
      },
      {
        id: 'l_05_4',
        title: 'Writing Performance Reviews',
        duration: '13 min',
        xp: 100,
        status: 'locked',
        skill: 'writing',
      },
      {
        id: 'l_05_5',
        title: 'Listening: Team Briefing',
        duration: '10 min',
        xp: 100,
        status: 'locked',
        skill: 'listening',
      },
      {
        id: 'l_05_6',
        title: 'Grammar: Advanced Tenses',
        duration: '10 min',
        xp: 100,
        status: 'locked',
        skill: 'grammar',
      },
    ],
  },
];

export const SKILL_COLOR: Record<string, string> = {
  speaking: '#C8102E',
  vocabulary: '#2563EB',
  writing: '#7C3AED',
  listening: '#059669',
  grammar: '#D97706',
};

export const SKILL_LABEL: Record<string, string> = {
  speaking: 'Speaking',
  vocabulary: 'Vocabulary',
  writing: 'Writing',
  listening: 'Listening',
  grammar: 'Grammar',
};
